logo:
  pose:
    position:
      x: 0.6689
      y: 1.2304
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
arrow_head:
  pose:
    position:
      x: 1.1770
      y: 0.4894
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0 
      z: -0.8682
      w: 0.4961
arrow_long:
  pose: 
    position:
      x: 0.7953
      y: 0.9755
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.4485
      w: 0.8937
            